/**
 * State-Specific Contractor Contract Requirements
 *
 * Each state has unique legal requirements for home improvement / contractor
 * service agreements. This module provides the data needed to generate
 * state-compliant contracts.
 *
 * Sources: State home improvement contract acts, contractor licensing boards,
 * FTC cooling-off rule (16 CFR Part 429), and state consumer protection statutes.
 *
 * NOTE: This is software-generated guidance, not legal advice. Always recommend
 * attorney review for high-value or complex projects.
 */

export interface StateContractorRequirements {
  name: string;
  hasHomeImprovementAct: boolean;
  statuteName?: string;
  cancellationDays: number;
  cancellationNoticeRequired: boolean;
  cancellationNoticeText?: string;
  maxDepositPercent: number | null;
  maxDepositFlat: number | null;
  depositRule?: string;
  preliminaryLienNoticeRequired: boolean;
  preliminaryLienNoticeDays?: number;
  lienNoticeText?: string;
  licenseDisplayRequired: boolean;
  licenseDisclosureText?: string;
  licensingBoard?: string;
  writtenContractRequired: boolean;
  writtenContractThreshold?: number;
  requiredDisclosures: string[];
  warrantyRequirements?: string;
  changeOrderRules?: string;
  complianceNotes: string[];
}

export const STATE_CONTRACTOR_REQUIREMENTS: Record<string, StateContractorRequirements> = {
  AL: { name: 'Alabama', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Alabama Licensing Board for General Contractors', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['Contractor license number must appear on all contracts and advertisements.'], complianceNotes: ['Projects over $50,000 require a licensed general contractor', 'Residential work over $10,000 requires a licensed residential home builder'] },
  AK: { name: 'Alaska', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Alaska Division of Corporations, Business and Professional Licensing', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: [], complianceNotes: ['General contractors must be registered with the state'] },
  AZ: { name: 'Arizona', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, depositRule: 'No statutory cap, but Registrar of Contractors can take action for excessive deposits.', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 20, lienNoticeText: 'Arizona law requires contractors to provide a 20-day preliminary lien notice to the property owner before filing a mechanic\'s lien.', licenseDisplayRequired: true, licenseDisclosureText: 'Licensed by the Arizona Registrar of Contractors, License #[NUMBER].', licensingBoard: 'Arizona Registrar of Contractors (ROC)', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['ROC license number must appear on all contracts.', 'Contract must include the Registrar of Contractors phone number: (602) 542-1525.', 'Contract must state: "Homeowners may contact the Registrar of Contractors with questions or complaints at www.roc.az.gov."'], complianceNotes: ['All contractors must be licensed through the Arizona Registrar of Contractors', 'Residential contracts over $1,000 must be in writing'] },
  AR: { name: 'Arkansas', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Arkansas Contractors Licensing Board', writtenContractRequired: true, writtenContractThreshold: 2000, requiredDisclosures: [], complianceNotes: ['Residential contractors must be licensed for projects over $2,000'] },
  CA: { name: 'California', hasHomeImprovementAct: true, statuteName: 'California Home Improvement Act (Bus. & Prof. Code §7150-7168)', cancellationDays: 3, cancellationNoticeRequired: true, cancellationNoticeText: 'You, the buyer, may cancel this transaction at any time prior to midnight of the third business day after the date of this transaction. See the attached notice of cancellation form for an explanation of this right.', maxDepositPercent: 10, maxDepositFlat: 1000, depositRule: 'Down payment cannot exceed $1,000 or 10% of the contract price, whichever is less (Bus. & Prof. Code §7159.5).', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 20, lienNoticeText: 'California law requires that any contractor, subcontractor, or material supplier who has not been paid may record a mechanic\'s lien on the property. A 20-day preliminary notice is required.', licenseDisplayRequired: true, licenseDisclosureText: 'Contractors are required by law to be licensed and regulated by the Contractors\' State License Board (CSLB). Any questions concerning a contractor may be referred to the Registrar, Contractors\' State License Board, P.O. Box 26000, Sacramento, CA 95826.', licensingBoard: 'Contractors State License Board (CSLB)', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['Contract must include the CSLB license number.', 'Three-day right to cancel notice must be attached for door-to-door sales.', 'Contract must state start and completion dates.', 'Payment schedule must not exceed the value of work performed.'], warrantyRequirements: 'California law provides an implied warranty of fitness lasting at least one year. Patent defects: 4 years. Latent defects: 10 years.', changeOrderRules: 'All change orders must be in writing and signed by both parties (Bus. & Prof. Code §7159).', complianceNotes: ['All contracts over $500 must be in writing', 'Deposit cannot exceed $1,000 or 10% (whichever is less)', 'Must display CSLB license number on all contracts and advertising', 'Preliminary 20-day notice required to preserve lien rights'] },
  CO: { name: 'Colorado', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state contractor licensing requirement (local municipalities may require)'] },
  CT: { name: 'Connecticut', hasHomeImprovementAct: true, statuteName: 'Connecticut Home Improvement Act (Conn. Gen. Stat. §20-418 to §20-432)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'Initial deposit cannot exceed 1/3 of the total contract price. No payment can be demanded until work is commenced.', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Connecticut Home Improvement Contractor Registration #[NUMBER]', licensingBoard: 'Connecticut Department of Consumer Protection', writtenContractRequired: true, writtenContractThreshold: 200, requiredDisclosures: ['Contract must include contractor registration number.', 'Contract must include start and completion dates.', 'Notice of cancellation rights must be included.'], complianceNotes: ['Home improvement contractors must be registered', 'Written contracts required for all work over $200', 'Deposit cannot exceed 1/3 of total price'] },
  DE: { name: 'Delaware', hasHomeImprovementAct: true, statuteName: 'Delaware Home Improvement Fraud Prevention Act', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['Written contract required for all home improvement work over $500.'], complianceNotes: ['No state licensing requirement for most contractors', 'Written contract required for work over $500'] },
  FL: { name: 'Florida', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 10, maxDepositFlat: null, depositRule: 'Initial payment cannot exceed 10% of the contract price or the cost of materials ordered, whichever is greater (Fla. Stat. §489.126).', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 45, lienNoticeText: 'ACCORDING TO FLORIDA\'S CONSTRUCTION LIEN LAW (SECTIONS 713.001-713.37, FLORIDA STATUTES), THOSE WHO WORK ON YOUR PROPERTY OR PROVIDE MATERIALS AND ARE NOT PAID IN FULL HAVE A RIGHT TO ENFORCE THEIR CLAIM FOR PAYMENT AGAINST YOUR PROPERTY.', licenseDisplayRequired: true, licenseDisclosureText: 'Licensed and insured. Florida License #[NUMBER].', licensingBoard: 'Florida Construction Industry Licensing Board (CILB)', writtenContractRequired: true, writtenContractThreshold: 2500, requiredDisclosures: ['Florida Building Code requires permits for most construction work.', 'Owner\'s lien rights notice is required on all contracts.', 'Contractor must include license number on all contracts.'], warrantyRequirements: 'Florida provides a 4-year statute of limitations for latent defects and 15 years for structural defects.', complianceNotes: ['Contractors must be licensed by the CILB', 'Initial deposit limited to 10% of contract price', 'Preliminary notice (Notice to Owner) required within 45 days'] },
  GA: { name: 'Georgia', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 30, lienNoticeText: 'Georgia law requires that within 30 days of beginning work, the contractor must file a notice of commencement to preserve lien rights.', licenseDisplayRequired: true, licensingBoard: 'Georgia Residential and General Contractors Board', writtenContractRequired: true, writtenContractThreshold: 2500, requiredDisclosures: ['Residential and general contractor license number required on contracts.'], complianceNotes: ['Residential and general contractors must be licensed for work over $2,500'] },
  HI: { name: 'Hawaii', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Hawaii Contractors License Board', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['License number must appear on all contracts and advertising.'], complianceNotes: ['All contractors must be licensed regardless of project size'] },
  ID: { name: 'Idaho', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Idaho Bureau of Occupational Licenses', writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['Public works contractors must be licensed'] },
  IL: { name: 'Illinois', hasHomeImprovementAct: true, statuteName: 'Illinois Home Repair and Remodeling Act (815 ILCS 513)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 60, lienNoticeText: 'Illinois Mechanics Lien Act (770 ILCS 60) provides that subcontractors and material suppliers must serve notice within 60 days of first furnishing labor or materials to preserve lien rights.', licenseDisplayRequired: false, writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['The Home Repair and Remodeling Act requires specific disclosures for residential projects.'], complianceNotes: ['No state licensing requirement (Chicago and some municipalities require)', 'Written contract required for work over $1,000'] },
  IN: { name: 'Indiana', hasHomeImprovementAct: true, statuteName: 'Indiana Home Improvement Contracts Act (IC 24-5-11)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: true, writtenContractThreshold: 150, requiredDisclosures: ['Written contract required for home improvements over $150.', 'Contract must include start and completion dates.'], complianceNotes: ['Home improvement contracts over $150 must be in writing'] },
  IA: { name: 'Iowa', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 30, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement for most contractors', 'Preliminary lien notice required within 30 days'] },
  KS: { name: 'Kansas', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement (municipalities may require)'] },
  KY: { name: 'Kentucky', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing for residential contractors (some cities require)'] },
  LA: { name: 'Louisiana', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Louisiana State Licensing Board for Contractors', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['License number must appear on contracts.'], complianceNotes: ['Contractors must be licensed for residential work over $75,000'] },
  ME: { name: 'Maine', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement'] },
  MD: { name: 'Maryland', hasHomeImprovementAct: true, statuteName: 'Maryland Home Improvement Law (Bus. Reg. §8-101 to §8-803)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'No payment can exceed 1/3 of the contract price before work begins (Md. Code, Bus. Reg. §8-611).', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Maryland Home Improvement Commission (MHIC) License #[NUMBER]', licensingBoard: 'Maryland Home Improvement Commission (MHIC)', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['MHIC license number required on all contracts.', 'Contract must include start and completion dates.', 'Three-day right to cancel notice must be included.'], complianceNotes: ['All home improvement contractors must be licensed through MHIC', 'Down payment cannot exceed 1/3 of contract price'] },
  MA: { name: 'Massachusetts', hasHomeImprovementAct: true, statuteName: 'Massachusetts Home Improvement Contractor Act (M.G.L. c.142A)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'No initial payment can exceed 1/3 of the total price. Progress payments cannot exceed value of work performed plus materials on-site.', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Massachusetts Home Improvement Contractor Registration #[NUMBER]', licensingBoard: 'Massachusetts Office of Consumer Affairs', writtenContractRequired: true, writtenContractThreshold: 0, requiredDisclosures: ['HIC registration number must appear on all contracts.', 'Contract must include the right to cancel notice.', 'Contract must include start and completion dates.', 'Owner cannot be asked to sign a completion certificate until work is complete.'], complianceNotes: ['All home improvement contractors must be registered', 'Written contract required for ALL home improvement work', 'Deposit cannot exceed 1/3 of total price'] },
  MI: { name: 'Michigan', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 20, lienNoticeText: 'Michigan Construction Lien Act (MCL 570.1101-1305) provides that any contractor, subcontractor, or supplier who provides labor or materials may have a right to file a construction lien against the improved property if not paid.', licenseDisplayRequired: true, licensingBoard: 'Michigan Licensing and Regulatory Affairs (LARA)', writtenContractRequired: true, writtenContractThreshold: 600, requiredDisclosures: ['Residential builder or maintenance and alteration license number required.'], complianceNotes: ['Residential builders and maintenance/alteration contractors must be licensed', 'Written contract required for work over $600'] },
  MN: { name: 'Minnesota', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 45, licenseDisplayRequired: true, licensingBoard: 'Minnesota Department of Labor and Industry', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['License number must appear on all contracts.'], complianceNotes: ['Residential building contractors must be licensed'] },
  MS: { name: 'Mississippi', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Mississippi State Board of Contractors', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: [], complianceNotes: ['Contractors must be licensed for projects over $50,000'] },
  MO: { name: 'Missouri', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement (some cities require)'] },
  MT: { name: 'Montana', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 20, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement', 'Preliminary notice required within 20 days'] },
  NE: { name: 'Nebraska', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement (Omaha and Lincoln require)'] },
  NV: { name: 'Nevada', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 10, maxDepositFlat: null, depositRule: 'For residential work: initial deposit cannot exceed 10% of the contract price or the cost of special-order materials (NRS 624.609).', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 31, lienNoticeText: 'Nevada law provides for mechanics liens. Subcontractors and suppliers must provide a preliminary lien notice within 31 days of first furnishing labor or materials.', licenseDisplayRequired: true, licenseDisclosureText: 'Nevada State Contractors Board License #[NUMBER]', licensingBoard: 'Nevada State Contractors Board (NSCB)', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['NSCB license number must appear on all contracts.'], complianceNotes: ['All contractors must be licensed through NSCB', 'Deposit limited to 10% for residential work'] },
  NH: { name: 'New Hampshire', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement for general contractors'] },
  NJ: { name: 'New Jersey', hasHomeImprovementAct: true, statuteName: 'New Jersey Contractor Registration Act (N.J.S.A. 56:8-136 to 56:8-152)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'Deposit cannot exceed 1/3 of the total contract price.', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'NJ Home Improvement Contractor Registration #13VH[NUMBER]', licensingBoard: 'New Jersey Division of Consumer Affairs', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['NJ HIC registration number (13VH format) must appear on all contracts.', 'Three-day right to cancel must be disclosed.', 'Contract must include start and completion dates.', 'Contract must include payment schedule.'], complianceNotes: ['All home improvement contractors must be registered', 'Deposit cannot exceed 1/3 of contract price', 'Written contract required for work over $500'] },
  NM: { name: 'New Mexico', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 60, licenseDisplayRequired: true, licensingBoard: 'New Mexico Construction Industries Division (CID)', writtenContractRequired: true, writtenContractThreshold: 5000, requiredDisclosures: ['CID license number must appear on contracts.'], complianceNotes: ['Contractors must be licensed for work over $5,000'] },
  NY: { name: 'New York', hasHomeImprovementAct: true, statuteName: 'New York Home Improvement Business Act (Gen. Bus. Law Art. 36-A)', cancellationDays: 3, cancellationNoticeRequired: true, cancellationNoticeText: 'You may cancel this contract at any time before midnight of the third business day after the day on which you signed this contract. To cancel, mail or deliver a signed and dated copy of a cancellation notice to the contractor at the address shown on this contract.', maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'No initial deposit can exceed 1/3 of the total contract price.', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 30, lienNoticeText: 'New York Lien Law provides that contractors, subcontractors, and material suppliers who are not paid may file a mechanics lien against the property.', licenseDisplayRequired: true, licenseDisclosureText: 'Licensed Home Improvement Contractor, Registration #[NUMBER]', licensingBoard: 'New York Secretary of State / Local County Licensing', writtenContractRequired: true, writtenContractThreshold: 0, requiredDisclosures: ['County home improvement contractor registration number must be displayed.', 'Three-day right to cancel notice is mandatory.', 'Contract must include estimated start and completion dates.', 'NYC additionally requires a Department of Consumer Affairs license.'], complianceNotes: ['Home improvement contractors must register in the county where work is performed', 'NYC requires a DCWP license', 'Written contract required for ALL home improvement work', 'Deposit cannot exceed 1/3 of contract price'] },
  NC: { name: 'North Carolina', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 120, lienNoticeText: 'North Carolina law provides for mechanics liens. A Notice to Lien Agent must be filed by subcontractors within 15 days of first furnishing labor or materials.', licenseDisplayRequired: true, licensingBoard: 'North Carolina Licensing Board for General Contractors', writtenContractRequired: true, writtenContractThreshold: 30000, requiredDisclosures: ['License number required on contracts for projects requiring a license.'], complianceNotes: ['General contractors must be licensed for projects over $30,000'] },
  ND: { name: 'North Dakota', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'North Dakota Secretary of State', writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['Contractors must register with the Secretary of State'] },
  OH: { name: 'Ohio', hasHomeImprovementAct: true, statuteName: 'Ohio Home Solicitation Sales Act (ORC §1345.21-1345.28)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 21, licenseDisplayRequired: false, writtenContractRequired: true, writtenContractThreshold: 25, requiredDisclosures: ['Right to cancel notice required for door-to-door sales.'], complianceNotes: ['No state licensing for residential contractors (some cities require)'] },
  OK: { name: 'Oklahoma', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 75, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing for residential contractors'] },
  OR: { name: 'Oregon', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: 1000, depositRule: 'Initial deposit cannot exceed $1,000 or the actual cost of materials ordered, whichever is greater (ORS 701.305).', preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 8, lienNoticeText: 'Oregon law (ORS 87.007) requires an "Information Notice to Owner" to be provided to the property owner at the time of contracting.', licenseDisplayRequired: true, licenseDisclosureText: 'Oregon Construction Contractors Board (CCB) License #[NUMBER]', licensingBoard: 'Oregon Construction Contractors Board (CCB)', writtenContractRequired: true, writtenContractThreshold: 2000, requiredDisclosures: ['CCB license number must appear on all contracts.', '"Information Notice to Owner" must be provided at time of contracting.'], complianceNotes: ['All contractors must be licensed through the CCB', 'Deposit limited to $1,000 or actual material cost'] },
  PA: { name: 'Pennsylvania', hasHomeImprovementAct: true, statuteName: 'Pennsylvania Home Improvement Consumer Protection Act (73 P.S. §517.1-517.19)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'Initial deposit cannot exceed 1/3 of the total contract price.', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Pennsylvania Home Improvement Contractor Registration #PA[NUMBER]', licensingBoard: 'Pennsylvania Attorney General\'s Office', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['PA HIC registration number must appear on all contracts.', 'Contract must include start and completion dates.', 'Three-day right to cancel notice is required.'], complianceNotes: ['All home improvement contractors must register with the AG\'s office', 'Deposit cannot exceed 1/3 of contract price'] },
  RI: { name: 'Rhode Island', hasHomeImprovementAct: true, statuteName: 'Rhode Island Contractors\' Registration and Licensing Board (R.I.G.L. §5-65)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'Rhode Island Contractors\' Registration and Licensing Board', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['Registration number must appear on all contracts.'], complianceNotes: ['All contractors must be registered and licensed'] },
  SC: { name: 'South Carolina', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'South Carolina Contractors Licensing Board', writtenContractRequired: true, writtenContractThreshold: 5000, requiredDisclosures: ['License number required on contracts for licensed work.'], complianceNotes: ['General and mechanical contractors must be licensed for work over $5,000'] },
  SD: { name: 'South Dakota', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement'] },
  TN: { name: 'Tennessee', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 90, licenseDisplayRequired: true, licensingBoard: 'Tennessee Board for Licensing Contractors', writtenContractRequired: true, writtenContractThreshold: 25000, requiredDisclosures: ['License number required on contracts for work requiring a license.'], complianceNotes: ['Contractors must be licensed for work over $25,000'] },
  TX: { name: 'Texas', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, cancellationNoticeText: 'You may cancel this contract without any penalty or obligation within 3 business days from the date of this contract.', maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 15, lienNoticeText: 'Texas Property Code Chapter 53 provides for mechanics and materialmen\'s liens. Notice must be provided by the 15th day of the second month following each month work was performed.', licenseDisplayRequired: false, writtenContractRequired: true, writtenContractThreshold: 0, requiredDisclosures: ['Texas Property Code §53.255 requires certain lien notices.', 'Disclosure of property owner\'s rights under Texas Residential Construction Commission Act.'], warrantyRequirements: 'Texas Property Code provides a 10-year statute of repose for residential construction defects.', complianceNotes: ['Texas does not license general contractors at the state level', 'Some trades (electricians, plumbers, HVAC) require state licensing', 'Written contract strongly recommended for all work'] },
  UT: { name: 'Utah', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 20, licenseDisplayRequired: true, licensingBoard: 'Utah Division of Occupational and Professional Licensing (DOPL)', writtenContractRequired: true, writtenContractThreshold: 2000, requiredDisclosures: ['License number must appear on contracts.', 'State Construction Registry filing required for projects over $2,000.'], complianceNotes: ['All contractors must be licensed through DOPL'] },
  VT: { name: 'Vermont', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement for general contractors', 'Residential contractors must register with Secretary of State'] },
  VA: { name: 'Virginia', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Virginia Contractor License #[NUMBER], Class [A/B/C]', licensingBoard: 'Virginia Board for Contractors (DPOR)', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['Contractor license number and class must appear on contracts.'], complianceNotes: ['Contractors must be licensed (Class A: >$120K; Class B: $10K-$120K; Class C: $1K-$10K)'] },
  WA: { name: 'Washington', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: true, preliminaryLienNoticeDays: 60, lienNoticeText: 'Washington law (RCW 60.04) provides for construction liens. Any person furnishing labor, materials, or equipment for improvements may file a claim of lien against the property.', licenseDisplayRequired: true, licenseDisclosureText: 'Washington State Contractor Registration #[NUMBER]', licensingBoard: 'Washington Department of Labor & Industries', writtenContractRequired: true, writtenContractThreshold: 1000, requiredDisclosures: ['Contractor registration number must appear on all contracts.', 'Contract must include the "Notice to Customer" regarding lien rights.', 'Contractor must disclose bond and insurance information.'], complianceNotes: ['All contractors must be registered with L&I', 'Bond and insurance required for registration'] },
  WV: { name: 'West Virginia', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licensingBoard: 'West Virginia Contractor Licensing Board', writtenContractRequired: true, writtenContractThreshold: 2500, requiredDisclosures: ['License number required on contracts for licensed work.'], complianceNotes: ['Contractors must be licensed for work over $2,500'] },
  WI: { name: 'Wisconsin', hasHomeImprovementAct: true, statuteName: 'Wisconsin Home Improvement Practices Act (Wis. Admin. Code ATCP 110)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 10, maxDepositFlat: null, depositRule: 'Contractor cannot require a down payment exceeding 10% of the estimated total price (ATCP 110.05).', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'Wisconsin Dwelling Contractor Qualifier Certification #[NUMBER]', licensingBoard: 'Wisconsin Department of Safety and Professional Services', writtenContractRequired: true, writtenContractThreshold: 500, requiredDisclosures: ['Dwelling contractor certification number required on contracts.', 'Contract must include start and completion dates.', 'Contract must include total price.'], complianceNotes: ['Dwelling contractors must be certified', 'Deposit limited to 10% of contract price'] },
  WY: { name: 'Wyoming', hasHomeImprovementAct: false, cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: null, maxDepositFlat: null, preliminaryLienNoticeRequired: false, licenseDisplayRequired: false, writtenContractRequired: false, requiredDisclosures: [], complianceNotes: ['No state licensing requirement for general contractors'] },
  DC: { name: 'District of Columbia', hasHomeImprovementAct: true, statuteName: 'DC Home Improvement Law (DC Code §28-3814)', cancellationDays: 3, cancellationNoticeRequired: true, maxDepositPercent: 33, maxDepositFlat: null, depositRule: 'Deposit cannot exceed 1/3 of the total contract price.', preliminaryLienNoticeRequired: false, licenseDisplayRequired: true, licenseDisclosureText: 'District of Columbia Basic Business License #[NUMBER]', licensingBoard: 'DC Department of Consumer and Regulatory Affairs (DCRA)', writtenContractRequired: true, writtenContractThreshold: 300, requiredDisclosures: ['DC business license number must appear on contracts.', 'Written contract required for all home improvement work over $300.', 'Three-day cancellation right must be disclosed.'], complianceNotes: ['All contractors must hold a DC Basic Business License', 'Deposit limited to 1/3 of contract price'] },
};

export function getStateRequirements(stateCode: string): StateContractorRequirements {
  const code = stateCode.toUpperCase().trim();
  return STATE_CONTRACTOR_REQUIREMENTS[code] || {
    name: stateCode,
    hasHomeImprovementAct: false,
    cancellationDays: 3,
    cancellationNoticeRequired: true,
    maxDepositPercent: null,
    maxDepositFlat: null,
    preliminaryLienNoticeRequired: false,
    licenseDisplayRequired: false,
    writtenContractRequired: false,
    requiredDisclosures: [],
    complianceNotes: [],
  };
}

export function validateDeposit(state: string, depositAmount: number, totalAmount: number): string | null {
  const reqs = getStateRequirements(state);
  if (reqs.maxDepositPercent !== null) {
    const maxByPercent = totalAmount * (reqs.maxDepositPercent / 100);
    if (reqs.maxDepositFlat !== null) {
      const effectiveMax = Math.min(reqs.maxDepositFlat, maxByPercent);
      if (depositAmount > effectiveMax) return `${reqs.name} law limits deposits to $${effectiveMax.toFixed(2)}. Your deposit of $${depositAmount.toFixed(2)} exceeds this limit.`;
    } else {
      if (depositAmount > maxByPercent) return `${reqs.name} law limits deposits to ${reqs.maxDepositPercent}% of the contract price ($${maxByPercent.toFixed(2)}). Your deposit exceeds this limit.`;
    }
  } else if (reqs.maxDepositFlat !== null) {
    if (depositAmount > reqs.maxDepositFlat) return `${reqs.name} law limits deposits to $${reqs.maxDepositFlat.toFixed(2)}. Your deposit exceeds this limit.`;
  }
  return null;
}

export function generateStateDisclosuresHtml(state: string, licenseNumber?: string): string {
  const reqs = getStateRequirements(state);
  const sections: string[] = [];

  if (reqs.cancellationNoticeRequired) {
    const text = reqs.cancellationNoticeText
      || 'YOU, THE BUYER, MAY CANCEL THIS CONTRACT AT ANY TIME PRIOR TO MIDNIGHT OF THE THIRD BUSINESS DAY AFTER THE DATE OF THIS TRANSACTION. To cancel, mail or deliver a signed and dated written notice to the contractor at the address shown on this contract no later than midnight of the third business day after you signed this contract. If you cancel, any payments made will be returned within ten (10) business days.';
    sections.push(`<div class="disclosure-box cancel-box"><p class="disclosure-title">⚖️ RIGHT TO CANCEL</p><p>${text}</p></div>`);
  }

  if (reqs.licenseDisplayRequired && reqs.licenseDisclosureText) {
    const licText = licenseNumber ? reqs.licenseDisclosureText.replace('#[NUMBER]', `#${licenseNumber}`).replace('[NUMBER]', licenseNumber) : reqs.licenseDisclosureText.replace('#[NUMBER]', '# ___________').replace('[NUMBER]', '___________');
    sections.push(`<div class="disclosure-box license-box"><p class="disclosure-title">📋 CONTRACTOR LICENSE</p><p>${licText}</p>${reqs.licensingBoard ? `<p class="disclosure-meta">Regulated by: ${reqs.licensingBoard}</p>` : ''}</div>`);
  }

  if (reqs.preliminaryLienNoticeRequired && reqs.lienNoticeText) {
    sections.push(`<div class="disclosure-box lien-box"><p class="disclosure-title">🏠 PROPERTY LIEN NOTICE</p><p>${reqs.lienNoticeText}</p></div>`);
  }

  if (reqs.depositRule) {
    sections.push(`<div class="disclosure-box deposit-box"><p class="disclosure-title">💰 DEPOSIT LIMITATIONS</p><p>${reqs.depositRule}</p></div>`);
  }

  if (reqs.requiredDisclosures.length > 0) {
    const items = reqs.requiredDisclosures.map(d => `<li>${d}</li>`).join('');
    sections.push(`<div class="disclosure-box additional-box"><p class="disclosure-title">📄 ${reqs.name.toUpperCase()} REQUIRED DISCLOSURES</p><ul>${items}</ul></div>`);
  }

  if (reqs.hasHomeImprovementAct && reqs.statuteName) {
    sections.push(`<div class="disclosure-box statute-box"><p class="disclosure-title">📜 GOVERNING STATUTE</p><p>This contract is subject to the requirements of the <strong>${reqs.statuteName}</strong>. Both parties acknowledge their rights and obligations under this statute.</p></div>`);
  }

  if (sections.length === 0) return '';

  return `<div class="state-disclosures"><h2 class="section-heading">STATE-SPECIFIC DISCLOSURES — ${reqs.name.toUpperCase()}</h2><p class="section-intro">The following disclosures are required by ${reqs.name} law and are incorporated into this Agreement:</p>${sections.join('')}</div>`;
}
